<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>import on Silviu's Blog</title><link>https://silviuvulcan.ro/blog/tags/import/</link><description>Recent content in import on Silviu's Blog</description><generator>Hugo -- gohugo.io</generator><language>en-us</language><lastBuildDate>Mon, 05 May 2014 05:44:19 +0000</lastBuildDate><atom:link href="https://silviuvulcan.ro/blog/tags/import/index.xml" rel="self" type="application/rss+xml"/><item><title>Using a standard mysql function returns an error</title><link>https://silviuvulcan.ro/blog/2014/05/05/using-a-standard-mysql-function-returns-an-error/</link><pubDate>Mon, 05 May 2014 05:44:19 +0000</pubDate><guid>https://silviuvulcan.ro/blog/2014/05/05/using-a-standard-mysql-function-returns-an-error/</guid><description>While running some mysql scripts I suddenly hit the following error:
ERROR 1305 (42000) at line 1: FUNCTION somedatabase.find_in_set does not exist Since find_in_set is a standard function I was kind of puzzled, especially since I ran the same script before on some other servers without error. Checking the SQL script I found the issue:
I had
update [blah blah] where find_in_set (id,(select [more blah[)) from [rest of blag]; and it has to be</description></item><item><title>Got a packet bigger than ‘max_allowed_packet’ bytes</title><link>https://silviuvulcan.ro/blog/2012/02/01/got-a-packet-bigger-than-max_allowed_packet-bytes/</link><pubDate>Wed, 01 Feb 2012 09:02:49 +0000</pubDate><guid>https://silviuvulcan.ro/blog/2012/02/01/got-a-packet-bigger-than-max_allowed_packet-bytes/</guid><description>I got this on a newly installed server when I tried to import a database:
[root@host ~]# mysql -u user -pPassword database &amp;lt; database.sql Enter password: ERROR 1153 (08S01) at line 53: Got a packet bigger than &amp;#39;max_allowed_packet&amp;#39; bytes It&amp;rsquo;s easily fixable. The default is probably 16M, I added the following in /etc/my.cnf
max_allowed_packet=32M And restarted mysql (depending on your distro you will do this differently):
service mysqld restart</description></item><item><title>After importing products from CSV in Virtuemart a discount is showed</title><link>https://silviuvulcan.ro/blog/2010/11/29/after-importing-products-from-csv-in-virtuemart-a-discount-is-showed/</link><pubDate>Mon, 29 Nov 2010 18:21:26 +0000</pubDate><guid>https://silviuvulcan.ro/blog/2010/11/29/after-importing-products-from-csv-in-virtuemart-a-discount-is-showed/</guid><description>After importing products into Virtuemart using CSV Import a discount is shown being available - although offering the same price as the list price. This happens because no discount id is set in the table. Running the following on the mysql table fixes that:
UPDATE `jos_vm_product` SET `product_discount_id`=0 WHERE 1</description></item></channel></rss>