<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>function on Silviu's Blog</title><link>https://silviuvulcan.ro/blog/tags/function/</link><description>Recent content in function on Silviu's Blog</description><generator>Hugo -- gohugo.io</generator><language>en-us</language><lastBuildDate>Mon, 05 May 2014 05:44:19 +0000</lastBuildDate><atom:link href="https://silviuvulcan.ro/blog/tags/function/index.xml" rel="self" type="application/rss+xml"/><item><title>Using a standard mysql function returns an error</title><link>https://silviuvulcan.ro/blog/2014/05/05/using-a-standard-mysql-function-returns-an-error/</link><pubDate>Mon, 05 May 2014 05:44:19 +0000</pubDate><guid>https://silviuvulcan.ro/blog/2014/05/05/using-a-standard-mysql-function-returns-an-error/</guid><description>While running some mysql scripts I suddenly hit the following error:
ERROR 1305 (42000) at line 1: FUNCTION somedatabase.find_in_set does not exist Since find_in_set is a standard function I was kind of puzzled, especially since I ran the same script before on some other servers without error.Â Checking the SQL script I found the issue:
I had
update [blah blah] where find_in_set (id,(select [more blah[)) from [rest of blag]; and it has to be</description></item></channel></rss>